# basic

In [1]:
import pandas as pd

## Series

In [2]:
dic = {
    "name":["python","c","dart"],
    "pop":[1021,2309,842],
    "rank": [4,1,4]
}

var1 = pd.Series(dic)
var1

name    [python, c, dart]
pop     [1021, 2309, 842]
rank            [4, 1, 4]
dtype: object

In [3]:
#  seires with single value
s = pd.Series(12, index=[0,1,2])
s

0    12
1    12
2    12
dtype: int64

## location based indexing `df.loc[row_indexer, column_indexer]`

In [28]:

s1 = pd.Series([12,23,54,21,4,6,78,9])
s1

0    12
1    23
2    54
3    21
4     4
5     6
6    78
7     9
dtype: int64

In [24]:
print(s1.loc[[0,2,4]])

0    12
2    54
4     4
dtype: int64

In [30]:

s2 = pd.DataFrame({
    "name":["python","c","dart", "java","ruby"],
    "pop":[1021,2309,842, 231, 122],
    "rank": [4,1,4,7,3]
} )
s2

     name   pop  rank
0  python  1021     4
1       c  2309     1
2    dart   842     4
3    java   231     7
4    ruby   122     3

In [ ]:
# get the row 3 and 4
s2.loc[[3,4]]

   name  pop  rank
3  java  231     7
4  ruby  122     3

In [33]:
# get the row 1 and 4

s2.loc[[1,4]]

   name   pop  rank
1     c  2309     1
4  ruby   122     3

In [34]:
# get the row 1 and 4 for the colun 'name' and 'rank'
s2.loc[[1,4], ['name', 'rank']]

   name  rank
1     c     1
4  ruby     3

In [35]:
# get me the all the rows for the column 'name' and 'pop'
s2.loc[:, ['name', 'pop']]

     name   pop
0  python  1021
1       c  2309
2    dart   842
3    java   231
4    ruby   122

In [36]:
# get me the all the rows for the column 'name' and 'pop' where rank is greater than 3
s2.loc[s2['rank'] > 3, ['name', 'pop']]

     name   pop
0  python  1021
2    dart   842
3    java   231

In [38]:
# get the 2nd row and the pop
s2.loc[2,'pop']

842

In [42]:
calories = [420, 380, 390, 450, 500]
s3 = pd.DataFrame(calories)
s3

     0
0  420
1  380
2  390
3  450
4  500

In [44]:
s3.columns = ["calories"]
s3

   calories
0       420
1       380
2       390
3       450
4       500

In [45]:
s3.index = ["day1", "day2", "day3", "day4", "day5"]
s3

      calories
day1       420
day2       380
day3       390
day4       450
day5       500

In [50]:
# get the day 4 calories
s3.loc["day4", "calories"]

450

In [52]:
# get the day 4 and 1 calories
s3.loc[["day4", "day1"]]

      calories
day4       450
day1       420

In [ ]:
s3.iloc[3] # iloc works in orginal indexing

calories    450
Name: day4, dtype: int64

## Dataframe

In [2]:
dict1 = {
    "name":["python","c","dart"],
    "pop":[1021,2309,842],
    "rank": [4,1,4]
}

var1 = pd.DataFrame(dict1)
var1

     name   pop  rank
0  python  1021     4
1       c  2309     1
2    dart   842     4

In [4]:
var2 = pd.DataFrame(dict1, columns=["name"])
var2

     name
0  python
1       c
2    dart

In [5]:
var1

     name   pop  rank
0  python  1021     4
1       c  2309     1
2    dart   842     4

In [6]:
var1['name'][2]

'dart'

In [7]:
var1['pop'][2]

842

In [8]:
var1[['name','pop']]

     name   pop
0  python  1021
1       c  2309
2    dart   842

In [9]:
df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
                  index=['cobra', 'viper', 'sidewinder'],
                  columns=['max_speed', 'shield'])
df

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8